### Variables
@id =
@name= test
@address = test

### Get all stands
GET http://localhost:8080/stands HTTP/1.1

### Create stand
POST http://localhost:8080/stands HTTP/1.1
Content-Type: application/json

{
    "id": null,
    "name": "{{name}}",
    "address": "{{address}}"
}