name: Improve Docker build custom action
description: This is a custom action to improve the docker build using inputs 
inputs:
  path_dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Image Name"
    required: true
    default: "academy"
  tag_name:
    description: "Tag Name"
    required: false
    
runs:
  using: composite
  steps:
    - name: Create Docker image
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
            export TAG=$(date +%s)
        else
            export TAG="${{ inputs.tag_name }}"
        fi

        docker build . --file ${{ inputs.path_dockerfile }} --tag ${{ inputs.image_name }}:$TAG
      shell: bash
